name: Install VulkanSDK

inputs:
  version:
    required: true
    description: The version of the VulkanSDK to build. use 'latest' to use the live development option.

runs:
  using: 'composite'

  steps:
    - uses: actions/cache@v3
      with:
        path: |
          ${{github.workspace}}/gtest
          ${{github.workspace}}/vk_cache
        key: __${{runner.os}}vulkan${{inputs.version}}_
        restore-keys: |
          __${{runner.os}}vulkan__
          __vulkan__

    - name: Install Dependencies
      shell: bash
      run: |
        if [[ $RUNNER_OS == "Linux" ]]; then
          echo "Installing Dependencies"
        fi

    - name: Build Directory Structure
      shell: bash
      run: |
        cd ${{ github.workspace }}
        if [[ ! -d "vk_cache" ]]; then
          echo "Creating vk_cache directory"
          mkdir vk_cache
        fi
        cd vk_cache
        if [[ ! -d "build" ]]; then
          mkdir build
        fi
        if [[ ! -d "install" ]]; then
          mkdir install
        fi

    - name: Clone and Build Robin-Hood-Hashing
      shell: bash
      run: |
        cd ${{ github.workspace }}
        if [[ ! -d "rrhash" ]]; then
          git clone https://github.com/martinus/robin-hood-hashing rrhash
        else
          cd rrhash
          git pull
          cd ..
        fi
        cmake -Srrhash -Bvk_cache/build/rrhash -DCMAKE_BUILD_TYPE=RelWithDebInfo
        sudo cmake --build vk_cache/build/rrhash
        
    - name: Clone and Build SPIRV-Headers
      shell: bash
      run: |
        cd ${{ github.workspace }}/vk_cache
        if [[ ! -d "spv_headers" ]]; then
          git clone https://github.com/KhronosGroup/SPIRV-Headers spv_headers
        else
          cd spv_headers
          git pull
          cd ..
        fi
        cmake -Sspv_headers -Bbuild/spv_headers -DCMAKE_BUILD_TYPE=RelWithDebInfo
        sudo cmake --build build/spv_headers --target install

    - name: Clone and Build SPIRV-Tools
      shell: bash
      run: |
        cd ${{ github.workspace }}/vk_cache
        if [[ ! -d "spv_tools" ]]; then
          git clone https://github.com/KhronosGroup/SPIRV-Tools spv_tools
          git clone --depth=1 --branch v3.13.0.1 https://github.com/protocolbuffers/protobuf spv_tools/external/protobuf
        else
          cd spv_tools
          git pull
          cd ..
        fi
        cmake -Sspv_tools -Bbuild/spv_tools -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSPIRV_SKIP_TESTS=ON -DSPIRV-Headers_SOURCE_DIR=${{github.workspace}}/vk_cache/spv_headers
        sudo cmake --build build/spv_tools --target install

    - name: Clone and Build SPIRV-Reflect
      shell: bash
      run: |
        cd ${{ github.workspace }}/vk_cache
        if [[ ! -d "spv_reflect" ]]; then
          git clone https://github.com/KhronosGroup/SPIRV-Reflect spv_reflect
          git clone --depth=1 --branch v3.13.0.1 https://github.com/protocolbuffers/protobuf spv_reflect/external/protobuf
        else
          cd spv_reflect
          git pull
          cd external/protobuf
        fi
        git submodule update --init
        cd ../../..
        cmake -Sspv_reflect -Bbuild/spv_reflect -DCMAKE_BUILD_TYPE=RelWithDebInfo
        sudo cmake --build build/spv_reflect --target install

    - name: Clone and Build Vulkan-Headers
      shell: bash
      run: |
        cd ${{ github.workspace }}/vk_cache
        if [[ ! -d "vk_headers" ]]; then
          git clone https://github.com/KhronosGroup/Vulkan-Headers vk_headers
        else
          cd vk_headers
          git pull
          cd ..
        fi
        cmake -Svk_headers -Bbuild/vk_headers -DCMAKE_BUILD_TYPE=RelWithDebInfo
        sudo cmake --build build/vk_headers --target install

    #- name: Clone and Build glslang
    #- name: Clone and Build Vulkan-Loader
    #- name: Clone and Build Vulkan-ValidationLayers
    #- name: Clone and Build MoltenVK
    #- name: Clone and Build Vulkan-Tools
    #- name: Clone and Build Vulkan-Hpp
    #- name: Clone and Build Vulkan-ExtensionLayer
    #- name: Clone and Build Vulkan-MemoryModel
    #- name: Clone and Build SPIRV-Cross