name: Install VulkanSDK

inputs:
  version:
    required: true
    description: The version of the VulkanSDK to build. use 'latest' to use the live development option.

runs:
  using: 'composite'

  steps:
    - uses: actions/cache@v3
      with:
        path: |
          ${{github.workspace}}/gtest
          ${{github.workspace}}/vk_cache
        key: __${{runner.os}}vulkan${{inputs.version}}_
        restore-keys: |
          __${{runner.os}}vulkan__
          __vulkan__

    - name: Install Dependencies
      shell: bash
      run: |
        if [[ $RUNNER_OS == "Linux" ]]; then
          echo "Installing Dependencies"
          sudo apt install git build-essential libx11-xcb-dev libxkbcommon-dev libwayland-dev libxrandr-dev libegl1-mesa-dev libx11-dev
        fi

    - name: Build Directory Structure
      shell: bash
      run: |
        cd ${{ github.workspace }}
        if [[ ! -d "vk_cache" ]]; then
          echo "Creating vk_cache directory"
          mkdir vk_cache
        fi
        cd vk_cache
        if [[ ! -d "build" ]]; then
          mkdir build
        fi
        if [[ ! -d "install" ]]; then
          mkdir install
        fi

    - name: Clone and Build Robin-Hood-Hashing
      shell: bash
      run: |
        cd ${{ github.workspace }}
        if [[ ! -d "rrhash" ]]; then
          git clone https://github.com/martinus/robin-hood-hashing rrhash
        else
          cd rrhash
          git pull
          cd ..
        fi
        cmake -Srrhash -Bvk_cache/build/rrhash -DCMAKE_BUILD_TYPE=RelWithDebInfo
        sudo cmake --build vk_cache/build/rrhash
        
    - name: Clone and Build SPIRV-Headers
      shell: bash
      run: |
        cd ${{ github.workspace }}/vk_cache
        if [[ ! -d "spv_headers" ]]; then
          git clone https://github.com/KhronosGroup/SPIRV-Headers spv_headers
        else
          cd spv_headers
          git pull
          cd ..
        fi
        cmake -Sspv_headers -Bbuild/spv_headers -DCMAKE_BUILD_TYPE=RelWithDebInfo
        sudo cmake --build build/spv_headers --target install

    - name: Clone and Build SPIRV-Tools
      shell: bash
      run: |
        cd ${{ github.workspace }}/vk_cache
        if [[ ! -d "spv_tools" ]]; then
          git clone https://github.com/KhronosGroup/SPIRV-Tools spv_tools
          git clone --depth=1 --branch v3.13.0.1 https://github.com/protocolbuffers/protobuf spv_tools/external/protobuf
        else
          cd spv_tools
          git pull
          cd ..
        fi
        cmake -Sspv_tools -Bbuild/spv_tools -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSPIRV_SKIP_TESTS=ON -DSPIRV-Headers_SOURCE_DIR=${{github.workspace}}/vk_cache/spv_headers
        sudo cmake --build build/spv_tools --target install

    - name: Clona and Build GLSLang
      shell: bash
      run: |
        cd ${{ github.workspace }}/vk_cache
        if [[ ! -d "glslang" ]]; then
          git clone https://github.com/KhronosGroup/glslang
          git clone https://github.com/google/googletest glslang/External/googletest
        else
          cd glslang
          git pull
          cd ..
        fi
        cd glslang/External/googletest
        git checkout 0c400f67fcf305869c5fb113dd296eca266c9725
        cd ../../..
        cmake -Sglslang -Bbuild/glslang -DCMAKE_BUILD_TYPE=RelWithDebInfo
        sudo cmake --build build/glslang --target install

    - name: Clone and Build Vulkan-Headers
      shell: bash
      run: |
        cd ${{ github.workspace }}/vk_cache
        if [[ ! -d "vk_headers" ]]; then
          git clone https://github.com/KhronosGroup/Vulkan-Headers vk_headers
        else
          cd vk_headers
          git pull
          cd ..
        fi
        cmake -Svk_headers -Bbuild/vk_headers -DCMAKE_BUILD_TYPE=RelWithDebInfo
        sudo cmake --build build/vk_headers --target install

    - name: Clone and Build Vulkan-Loader
      shell: bash
      run: |
        cd ${{ github.workspace }}/vk_cache
        if [[ ! -d "vk_loader" ]]; then
          git clone https://github.com/KhronosGroup/Vulkan-Loader vk_loader
        else
          cd vk_loader
          git pull
          cd ..
        fi
        cmake -Svk_loader -Bbuild/vk_loader -DCMAKE_BUILD_TYPE=RelWithDebInfo
        sudo cmake --build build/vk_loader --target install

      - name: Clone and Build Vulkan-ExtensionLayer
        shell: bash
        run: |
          cd ${{github.workspace}}
          if [[ ! -d "vk_extension" ]]; then
            git clone https://github.com/KhronosGroup/Vulkan-ExtensionLayer vk_extension
          else
            cd vk_extension
            git pull 
            cd ..
          fi
          cmake -Svk_extension -Bbuild/vk_extension -DCMAKE_BUILD_TYPE=RelWithDebInfo
          sudo cmake --build build/vk_extension --target install
        
    #- name: Clone and Build Vulkan-ValidationLayers
    #- name: Clone and Build MoltenVK
    #- name: Clone and Build Vulkan-Tools
    #- name: Clone and Build Vulkan-Hpp
    #- name: Clone and Build Vulkan-MemoryModel
  